language: rust
rust:
  - stable

services:
  - docker

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - OS="linux"
    - os: osx
      env:
        - OS="darwin"

script:
  - python .travis/build.py
