[package]
name = "sbr-sys"
version = "0.1.0"
authors = ["maciejkula <maciej.kula@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
sbr = { path = "../sbr" }
const-cstr = "0.3.0"
libc = "0.2.41"
itertools = "0.7.8"
ndarray = { version = "0.11.0", features = ["blas", "serde-1"] }
blas-src = { version = "0.1.2", default-features = false, features = ["intel-mkl"] }
